### ISSUE TITLE
The device profile link is broken

### ISSUE THREAD

**Issue by ArchangelSDY** [MicrosoftDocs/vsts-rest-api-specs#590] opened 2023-02-06 13:42 UTC
The **Device Profile** link is broken:
https://learn.microsoft.com/en-us/resources/samples/active-directory-dotnet-deviceprofile/?v=17.23h

![image](https://user-images.githubusercontent.com/858914/216986817-bb8164fd-e3dc-4e96-820b-8e18cb665986.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a0ab71a0-a2df-fa37-83fa-080dece952f6
* Version Independent ID: f74b7d51-aede-ed93-437e-601654d8fa7e
* Content: [Get started with the REST APIs for Azure DevOps Services and Team Foundation Server - Azure DevOps Services REST API](https://learn.microsoft.com/en-us/rest/api/azure/devops/?view=azure-devops-rest-7.1)
* Content Source: [index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/index.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ecosystem**
* GitHub Login: @elbatk
* Microsoft Alias: **elbatk**

**Comment by nechvatalp** [comment] 2023-06-26 08:37
Duplicate of #434

**Closed by nechvatalp** 2023-06-26 08:37 UTC
Labels: documentation issue
