### ISSUE TITLE
API to get all builds based on repo/branch

### ISSUE THREAD

**Issue by ilantom** [MicrosoftDocs/vsts-rest-api-specs#599] opened 2023-04-27 23:30 UTC
I followed this doc: https://learn.microsoft.com/en-us/rest/api/azure/devops/build/builds/list?view=azure-devops-rest-7.0&source=docs to list all builds from a repository from a branch:

```
$parentUrl = "https://dev.azure.com/{organization}/{project}/_apis/build/builds?repository.type=TfsGit&repository.id=repoid&branchName=refs/heads/develop&api-version=6.0"
$parentData = Invoke-RestMethod -Uri $parentUrl -ContentType 'application/json' -Headers $headers -Method GET 
```

The issue I see is that the api is returning the builds that are not in my repository when the branchName is refs/heads/develop or refs/heads/main. Is this some known bug?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ec189039-ae2d-ca0f-eb18-c48c4b67378c
* Version Independent ID: d45d8053-0203-5c5a-f283-26acb4eed9c5
* Content: [Accounts REST API for Azure DevOps Services - Azure DevOps Services REST API](https://learn.microsoft.com/en-us/rest/api/azure/devops/build/builds/list?view=azure-devops-rest-7.0)
* Content Source: [[docs-ref-conceptual/7.0/account/index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-conceptual/7.0/account/index.md](https://learn.microsoft.com/en-us/rest/api/azure/devops/build/builds/list?view=azure-devops-rest-7.0))
* Service: **azure-devops**
* Sub-service: **azure-devops-ref**
* GitHub Login: @wnjenkin
* Microsoft Alias: **kaelli**

**Comment by nechvatalp** [comment] 2023-06-26 08:15
Closing as duplicate of #600

**Closed by nechvatalp** 2023-06-26 08:15 UTC
Labels: duplicate
