### ISSUE TITLE
Documentation link is 404

### ISSUE THREAD

**Issue by mday-ntirety** [MicrosoftDocs/vsts-rest-api-specs#586] opened 2023-01-17 22:57 UTC
The link to the documentation on this page is broken and leads to a 404 : https://learn.microsoft.com/en-us/vsts/search/overview

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4f03fe60-4750-dace-962b-9cd6b18bfb4f
* Version Independent ID: 5b08b31d-4955-52fe-4a1a-97d2f8c4907d
* Content: [Search REST API for Azure DevOps Services - Azure DevOps Services REST API](https://learn.microsoft.com/en-us/rest/api/azure/devops/search/?view=vsts-rest-tfs-4.1)
* Content Source: [docs-ref-conceptual/tfs-4.1/search/index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-conceptual/tfs-4.1/search/index.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ref**
* GitHub Login: @wnjenkin
* Microsoft Alias: **elbatk**

**Comment by nechvatalp** [comment] 2023-02-13 19:29
Duplicate of #555 closing

**Closed by nechvatalp** 2023-02-13 19:29 UTC
Labels: duplicate
