### ISSUE TITLE
Documentation link does not work

### ISSUE THREAD

**Issue by sivsubra** [MicrosoftDocs/vsts-rest-api-specs#573] opened 2022-11-12 22:19 UTC
Documentation link does not work

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ec4e73c0-8c8a-b95c-dff8-3810fd51faf1
* Version Independent ID: 85b08da1-23de-388d-b08d-5aefa587cc48
* Content: [Search REST API for Azure DevOps Services - Azure DevOps Services REST API](https://learn.microsoft.com/en-us/rest/api/azure/devops/search/?view=azure-devops-rest-7.0)
* Content Source: [docs-ref-conceptual/7.0/search/index.md](https://github.com/MicrosoftDocs/vsts-docs-rest-apis/blob/live/docs-ref-conceptual/7.0/search/index.md)
* Service: **azure-devops**
* Sub-service: **azure-devops-ref**
* GitHub Login: @wnjenkin
* Microsoft Alias: **pnechvatal**

**Comment by nechvatalp** [comment] 2023-02-13 19:29
Duplicate of #555 closing the duplicate

**Closed by nechvatalp** 2023-02-13 19:29 UTC
Labels: bug, duplicate, documentation issue
